version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/src
    depends_on:
      - db
    networks:
      - top-fruit-network

  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: top_fruit
      MYSQL_USER: topfruit
      MYSQL_PASSWORD: fruitpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - top-fruit-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - top-fruit-network

networks:
  top-fruit-network:
    driver: bridge

volumes:
  db_data: